### ISSUE TITLE
Setup "dialects" structure

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex-schema-inspector#2]
@kibertoad would you be able to run me through the structure and ideas of the main Knex repo (primarily "dialects")? I'd like to keep the general structure / lingo the same here as for the main project, but I'm not that familiar with the internals of Knex itself yet.. (Also down to hop on a zoom/meet/whatever call if that's easier 🙂 )

**Comment by kibertoad** [comment]
@rijkvanzanten Honestly, I would question everything about Knex structure, it was designed ages ago and not everything stood the test of time. And since knex instance with active connection probably should be passed as a dependency to inspector, I don't think we need dynamic driver resolution, instead we can do something like Strategy resolver based on client inside knex.

**Comment by kibertoad** [comment]
I think currently we mostly use Gitter for knex discussions, but I'm down to setup a Slack channel if you prefer that.

**Comment by rijkvanzanten** [comment]
I couldn't find you on Gitter 🤔 I'm down for Slack as well 👍
